name: code quality checks

on:
  pull_request:
  push: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  quality:
    name: build, test, analyze
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4
  
      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: restore dependencies
        run: dotnet restore src/Images-App/images-app.slnx
  
      - name: build (warnings as errors)
        run: dotnet build src/Images-App/images-app.slnx --no-restore --warnaserror
  
      - name: run test
        working-directory: src
        run: dotnet test src/Images-App/images-app.slnx --no-build --verbosity normal
  
      - name: Run static analysis (dotnet format)
        run: dotnet format --verify-no-changes
